export const defaultProject=()=>({
  version:'1.1',
  ui:{collapsed:{},showTextBoxes:false,snap:false,grid:10},
  measurePrefs:{unit:'px',ratio:1},
  layers:[{id:'layer-default',name:'Default',visible:true,locked:false}],
  activeLayerId:'layer-default',
  overlays:[],
  cropByPage:{},
  excludeVisible:true,
  textIndex:{},
  entityInspector:{
    scope:'current',
    selectedIds:[],
    hiddenIds:[],
    pinnedIds:[],
    showPins:true,
    showHiddenMasks:true,
    filters:{},
    columns:[],
    density:'compact'
  }
});
